id: IBBA58BDD
legacy_id: P005507
ocr_import_info:
  bdrc_scan_id: W22712
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T07:35:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T00:51:21.080140+00:00'
last_modified: 2022-09-02 08:51:38.261688
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22712
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22712
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: 'mnam med dwags po''i chos bzir grags pa''i gzun gi ''grel pa sning po gsal
    ba''i rgyan : a detailed study on sgam po pa''s chos bzi presentation of fundamental
    buddhist practice'
  author: ལ་ཡག་པ་བྱང་ཆུབ་དངོས་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.74364751338847
  ocr_word_median_confidence_index: 0.8199999928474426
quality: null
bases:
  I1613:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1613
      total_pages: 594
      volume_number: 1
      volume_pages_bdrc_intro: 3
    order: 1
    base_file: I1613.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.74364751338847
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
