id: IBBA58BDD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:36:50+00:00'
last_modified: '2022-06-08T03:34:39.877561+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22712
  title: མནམ་མེད་དྭགས་པོའི་ཆོས་བཟིར་གྲགས་པའི་གཟུན་གི་འགྲེལ་པ་སྣིང་པོ་གསལ་བའི་རྒྱན་༔་ཨ་དེཏཻལེད་སྟུདཡ་ཨོན་སྒམ་པོ་པའས་ཆོས་བཟི་པྲེསེནཏཏིཨོན་ཨོཕ༹་ཕུ༹ནདམེནཏལ་བུདདྷིསཏ་པྲཅཏིཅེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FA2C:
      image_group_id: I1613
      title: ''
      total_pages: 594
      order: 1
      base_file: FA2C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
