id: P005507
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:55:26.350239
source_metadata:
  id: bdr:W22712
  title: མནམ་མེད་དྭགས་པོའི་ཆོས་བཟིར་གྲགས་པའི་གཟུན་གི་འགྲེལ་པ་སྣིང་པོ་གསལ་བའི་རྒྱན་༔་ཨ་དེཏཻལེད་སྟུདཡ་ཨོན་སྒམ་པོ་པའས་ཆོས་བཟི་པྲེསེནཏཏིཨོན་ཨོཕ༹་ཕུ༹ནདམེནཏལ་བུདདྷིསཏ་པྲཅཏིཅེ
  author: ''
  volumes:
    2cc5c797779f4b2b9a31783298efffae:
      image_group_id: I1613
      title: ''
      volume_number: 1
      total_pages: 594
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
